@echo off
cd /d "C:\Users\SubratoBiswas\trinamix-conversion-workbench"
echo Cleaning any git locks...
del /f /q ".git\index.lock" 2>nul
del /f /q ".git\HEAD.lock" 2>nul
echo Dropping tracked bytecode...
git rm -r --cached --ignore-unmatch backend/app/__pycache__ backend/app/services/__pycache__ backend/app/parsers/__pycache__
echo Staging...
git add -A
echo Committing (no-op if clean)...
git commit -m "Dataset dedupe on upload: hash the uploaded file bytes (SHA-256, stored on Dataset.content_hash) and if a byte-identical dataset already exists, reuse it instead of creating a duplicate (drops the redundant copy). Stops the Datasets list filling with repeats of the same source extract."
echo Pushing...
git push origin main
echo.
echo ====== DONE - Press any key to close ======
pause
