@echo off
cd /d "C:\Users\SubratoBiswas\trinamix-conversion-workbench"
echo Cleaning any git locks...
del /f /q ".git\index.lock" 2>nul
del /f /q ".git\HEAD.lock" 2>nul
echo Dropping tracked bytecode...
git rm -r --cached --ignore-unmatch backend/app/__pycache__ backend/app/services/__pycache__ backend/app/parsers/__pycache__
echo Staging...
git add -A
echo Committing (no-op if clean)...
git commit -m "Persistent file storage via MongoDB: uploaded FBDI template bytes are now stored durably in Mongo (new fbdi_template_files collection) on upload, and re-parse rehydrates from Mongo when the ephemeral container disk has been wiped by a redeploy - so re-parse always works and no files are lost across deploys. No new infra or paid disk needed. (config still auto-detects a persistent disk mount as a bonus.)"
echo Pushing...
git push origin main
echo.
echo ====== DONE - Press any key to close ======
pause
