@echo off
cd /d "C:\Users\SubratoBiswas\trinamix-conversion-workbench"
echo Cleaning any git locks...
del /f /q ".git\index.lock" 2>nul
del /f /q ".git\HEAD.lock" 2>nul
echo Dropping tracked bytecode...
git rm -r --cached --ignore-unmatch backend/app/__pycache__ backend/app/services/__pycache__ backend/app/parsers/__pycache__
echo Staging...
git add -A
echo Committing (no-op if clean)...
git commit -m "defaults_service: use claude-haiku-4-5 for AI default inference (matches the working copilot path; avoids the ANTHROPIC_MODEL default that may be unavailable). Note: the AI fallback only fires for required+unmapped fields with no deterministic default; it currently stays dormant because control/learned/sequence defaults cover the supplier objects. Live diagnosis showed the configured ANTHROPIC_API_KEY on Render returns 401 invalid x-api-key, so any LLM call is swallowed and the endpoint falls back to deterministic defaults - key must be corrected in Render env for AI to activate."
echo Pushing...
git push origin main
echo.
echo ====== DONE - Press any key to close ======
pause
